# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
#defaults:
#   - override hydra/output_subdir: disabled  
#  - override hydra_logging: disabled
#  - override job_logging: disabled

output_subdir: null
# output directory, generated dynamically on each run
run:
  dir: ./results/${env.name}/${agent.name}/
sweep:
  dir: ./results/${env.name}/${agent.name}/
  subdir: ""
