#_target_: src.agents.sac.SACAgent
name: sac
parameters:
  reward_free: ${reward_free}
  obs_type: ??? # to be specified later
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  #num_expl_steps: ??? # to be specified later
  #action_bounds: ???
  batch_size: 256
  mem_size: 1e+6
  hidden_dim_critic: 300
  hidden_dim_actor: 300
  q_lr: 3e-4
  policy_lr: 3e-4
  tau: 0.005
  alpha: 0.1
  reward_scale: 1
  gamma: 0.99
  autotune: False
  learning_starts: 10
  policy_frequency: 2
  target_network_frequency: 1